version: '3.2'

services:
  packetbeat:
    build:
      context: extensions/packetbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    # Run as 'root' instead of 'packetbeat' (uid 1000) to allow reading
    # 'docker.sock' and the host's filesystem.
    user: root
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/filebeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false

    cap_add:
      - NET_ADMIN
    environment:
      - "WAIT_FOR_HOSTS=elasticsearch:9223 kibana:5667"
      - "HOST_ELASTICSEARCH=elasticsearch:9223"
      - "HOST_KIBANA=kibana:5667"
    
    network_mode: host
    
    volumes:
      - type: bind
        source: ./extensions/packetbeat/config/packetbeat.yml
        target: /usr/share/packetbeat/packetbeat.yml
        read_only: true
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
